from .admm_optim_ui_dictionnary import ADMM_UI_PARAMETERS
from .pytorch_optim_ui_dictionnary import PYTORCH_UI_PARAMETERS
from .pnp_optim_ui_dictionnary import PNP_UI_PARAMETERS
from .ppxa_optim_ui_dictionnary import PPXA_UI_PARAMETERS